site_practice/api/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('bbs/<int:pk>/comments/', comments),
    path('bbs/<int:pk>/', BbDetailView.as_view()),
    path('bbs/', bbs),
]

site_practice/main/urls.py
from django.urls import path
from .views import *

app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
    path('accounts/login/', BBLoginView.as_view(), name='login'),
    path('accounts/profile/change/<int:pk>/', profile_bb_change, name='profile_bb_change'),
    path('accounts/profile/delete/<int:pk>/', profile_bb_delete, name='profile_bb_delete'),
    path('accounts/profile/add/', profile_bb_add, name='profile_bb_add'),   # 34.5.2
    path('accounts/profile/<int:pk>/', profile_bb_detail, name='profile_bb_detail'),    # 34.5 для доступа к деталям объявлений созданных пользователем (для возврата на стр. пользователя кнопкой назад)
    path('accounts/profile/', profile, name='profile'),
    path('accounts/logout/', BBLogoutView.as_view(), name='logout'),
    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('account/password/change/', BBPasswordChangeView.as_view(), name='password_change'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('accounts/register/activate/<str:sign>/', user_activate, name='register_activate'),
    path('accounts/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
    path('<int:rubric_pk>/<int:pk>/', detail, name='detail'),   # для общего доступа к деталям объявлений со страници *по рубрикам*
    path('<int:pk>/', by_rubric, name='by_rubric'),     # если этот маршрут поместить после other_page то django примет этот адрес за имя шаблона страници other_page и выдаст 404
    path('<str:page>/', other_page, name='other'),      # порядок имеет значение
]

site_practice/site_practice/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('api/', include('api.urls')),
    path('', include('main.urls')),
]


if settings.DEBUG:
    # urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

site_practice/main/forms.py
from django import forms
from .models import *
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from .apps import user_registered
from django.forms import inlineformset_factory

from captcha.fields import CaptchaField     #35.3


class ChangeUserInfoForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')
    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'first_name', 'last_name', 'send_messages')


class RegisterUserForm(forms.ModelForm):    # 32.4 регистрация и активация пользователя
    email = forms.EmailField(required=True, label='Адрес электронной почты')    # полное объявление полей, которые хотим сделать обязательными для заполнения
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput, help_text=password_validation.password_validators_help_text_html()) # сообщение с требованиями к паролю осущ. всеми доступными в системе валидаторами
    password2 = forms.CharField(label='Пароль повторно', widget=forms.PasswordInput, help_text='Введите пароль еще раз')

    def clean_password1(self):  # метод выполняет валидацию пароля введенного в 1е поле
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):    # проверка на совпадение паролей осущ. только если 1й пароль прошел валидацию
        super().clean()
        password1 = self.cleaned_data['password1']      # если пароль левый qwerty123 то valid=False и вылетает ошибка на этой строке в дебагере, вместо того чтоб выдать сообщение об ошибке
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError('Введенные пароли не совпадают', code = 'password_mismatch')}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = False      # пользователь активен?
        user.is_activated = False   # пользователь прошел активацию? пока False пользователь не может выполнить вход
        if commit:
            user.save()         # сохраняем запись и закодированный пароль
        user_registered.send(RegisterUserForm, instance=user)   # сигнал для отправки письма активации. instance - параметр - это объект вновь созданного пользователя. Сигнал объявляется в модуле apps - этот модуль выполняется при инициализации приложения
        return user

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name', 'send_messages')


class SubRubricForm(forms.ModelForm):
    super_rubric = forms.ModelChoiceField(queryset=SuperRubric.objects.all(), empty_label=None, label='Надрубрики', required=True)

    class Meta:
        model = SubRubric
        fields = '__all__'


class SearchForm(forms.Form):   # у forms.Form нет атрибута save(), форма не связана с моделью
    keyword = forms.CharField(required=False, max_length=20, label='')


class BbForm(forms.ModelForm):  # 34.5 только ModelForm
    class Meta:
        model = Bb
        fields = '__all__'
        widgets = {'author': forms.HiddenInput}

AIFormSet = inlineformset_factory(Bb, AdditionalImage, fields='__all__')


class UserCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('is_active',)
        widgets = {'bb': forms.HiddenInput}


class GuestCommentForm(forms.ModelForm):
    captcha = CaptchaField(label='Введите текст с картинки', error_messages={'invalid': 'Неправельный текст'})

    class Meta:
        model = Comment
        exclude = ('is_active',)
        widgets = {'bb': forms.HiddenInput}

site_practice/main/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import UpdateView, CreateView, DeleteView    #32.3 редактирование данных пользователя
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, redirect
from django.views.generic.base import TemplateView  # 32.4.1.2
from django.core.signing import BadSignature    # 32.4.2
from django.contrib.auth import logout
from django.contrib import messages
from django.core.paginator import Paginator     # 34.4.1
from django.db.models import Q


from .models import *
from .forms import *
from .utilities import signer   #32.4.2


def index(request):
    bbs = Bb.objects.filter(is_active=True)[:10]
    context = {'bbs': bbs}
    return render(request, 'main/index.html', context)


def other_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


class BBLoginView(LoginView):
    template_name = 'main/login.html'


@login_required()   # 32.2.2. доступ только авторизованным пользователям
def profile(request):
    bbs = Bb.objects.filter(author=request.user.pk)     #  вывод объявлений оставленных текущим пользователем
    context = {'bbs': bbs}
    return render(request, 'main/profile.html', context)


class BBLogoutView(LoginRequiredMixin, LogoutView):     # LoginRequiredMixin примесь делающая контроллер класс доступным только авторизованным пользователям
    template_name = 'main/logout.html'


class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):  # 32.3
    model = AdvUser
    template_name = 'main/change_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('main:profile')
    success_message = 'Данные пользователя изменены'

    def setup(self, request, *args, **kwargs):  # наилучший способ получение ключа текущего пользователя
        self.user_id = request.user.pk          # сохраним ключ текущ. пользователя в атрибут user_id
        return super().setup(request, *args, **kwargs)

    def get_object(self, queryset=None):    # метод осуществляющий извлечение исправляемой записи по ключу user_id
        if not queryset:                    # если набор записей оказался пустым, получить набор записей
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)     # ищем запись пользователя в наборе


class BBPasswordChangeView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = 'main/password_change.html'
    success_url = reverse_lazy('main:profile')
    success_message = 'Пароль успешно изменен'


class RegisterUserView(CreateView):     # 32.4.1.2
    model = AdvUser
    template_name = 'main/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('main:register_done')


class RegisterDoneView(TemplateView):
    template_name = 'main/register_done.html'


def user_activate(request, sign):       # 32.4.2
    try:
        username = signer.unsign(sign)  # извлекаем имя пользователя из подписи
    except BadSignature:    # если подпись скомпрометирована -то сообщение об ошибке
        return render(request, 'main/bad_signature.html')
    user = get_object_or_404(AdvUser, username=username)  # берем запись польз из базы по имени
    if user.is_activated:
        template= 'main/user_is_activated.html'     # если пользователь уже активирован то сообщаем об этом
    else:
        template = 'main/activation_done.html'      # если не активирован, то активируем и сохраняем запись
        user.is_active = True
        user.is_activated = True
        user.save()
    return render(request, template)


class DeleteUserView(LoginRequiredMixin, DeleteView):
    model = AdvUser
    template_name = 'main/delete_user.html'
    success_url = reverse_lazy('main:index')

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        logout(request)
        messages.add_message(request, messages.SUCCESS, 'Пользователь удалён.')
        return super().post(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


def by_rubric(request, pk):
    rubric = get_object_or_404(SubRubric, pk=pk)
    bbs = Bb.objects.filter(is_active=True, rubric=pk)
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        q = Q(title__icontains=keyword) | Q(content__icontains=keyword)
        bbs = bbs.filter(q)
    else:
        keyword = ''
    form = SearchForm(initial={'keyword': keyword})
    paginator = Paginator(bbs, 2)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {'rubric': rubric, 'page': page, 'bbs': page.object_list, 'form': form}
    return render(request, 'main/by_rubric.html', context)


# def detail(request, rubric_pk, pk):
#     bb = get_object_or_404(Bb, pk=pk)
#     ais = bb.additionalimage_set.all()      # 34.4.2 additionalimage_set какой-то втроенный метод - перечень доп иллюстраций
#     context = {'bb': bb, 'ais': ais}
#     return render(request, 'main/detail.html', context)


@login_required
def profile_bb_detail(request, pk):
    bb = get_object_or_404(Bb, pk=pk)
    ais = bb.additionalimage_set.all()      # 34.4.2 additionalimage_set какой-то втроенный метод - перечень доп иллюстраций
    context = {'bb': bb, 'ais': ais}
    return render(request, 'main/profile_bb_detail.html', context)


@login_required
def profile_bb_add(request):
    if request.method == 'POST':
        form = BbForm(request.POST, request.FILES)
        if form.is_valid():
            bb = form.save()
            formset = AIFormSet(request.POST, request.FILES, instance=bb)
            if formset.is_valid():
                formset.save()
                messages.add_message(request, messages.SUCCESS, 'Объявление добавлено')
                return redirect('main:profile')
    else:
        form = BbForm(initial={'author': request.user.pk})
        formset = AIFormSet()
    context = {'form': form, 'formset':formset}
    return render(request, 'main/profile_bb_add.html', context)


@login_required
def profile_bb_change(request, pk):
    bb = get_object_or_404(Bb, pk=pk)
    if request.method == 'POST':
        form = BbForm(request.POST, request.FILES, instance=bb)
        if form.is_valid():
            bb = form.save()
            formset = AIFormSet(request.POST, request.FILES, instance=bb)
            if formset.is_valid():
                formset.save()
                messages.add_message(request, messages.SUCCESS, 'Объявление исправлено')
                return redirect('main:profile')
    else:
        form = BbForm(instance=bb)
        formset = AIFormSet(instance=bb)
    context = {'form': form, 'formset': formset}
    return render(request, 'main/profile_bb_change.html', context)


@login_required
def profile_bb_delete(request, pk):
    bb = get_object_or_404(Bb, pk=pk)
    if request.method == 'POST':
        bb.delete()
        messages.add_message(request, messages.SUCCESS, 'Объявление удалено')
        return redirect('main:profile')
    else:
        context = {'bb': bb}
        return render(request, 'main/profile_bb_delete.html', context)


def detail(request, rubric_pk, pk):     # 35.3
    bb = Bb.objects.get(pk=pk)
    ais = bb.additionalimage_set.all()
    comments = Comment.objects.filter(bb=pk, is_active=True)    # bb=pk? или же bb.pk
    initial = {'bb': bb.pk}
    if request.user.is_authenticated:
        initial['author'] = request.user.username
        form_class = UserCommentForm
    else:
        form_class = GuestCommentForm
    form = form_class(initial=initial)
    if request.method == 'POST':
        c_form = form_class(request.POST)
        if c_form.is_valid():
            c_form.save()
            messages.add_message(request, messages.SUCCESS, 'Комментарий добавлен')
        else:
            form = c_form
            messages.add_message(request, messages.WARNING, 'Комментарий не добавлен!')
    context = {'bb': bb,'ais': ais, 'comments': comments, 'form': form}
    return render(request, 'main/detail.html', context)

site_practice/main/templates/main/about.html
{% extends "main/layout/basic.html" %}

{% block title %}О сайте{% endblock %}

{% block content %}
<h2>О сайте</h2>
<p> учебный сайт для публикации объявлений</p>
{% endblock %}

site_practice/main/templates/main/bad_signature.html
{% extends "main/layout/basic.html" %}

{% block title %}Ошибка активации{% endblock %}

{% block content %}
<h2>Активация</h2>
<p>Активация пользователя с таким именем прошла неудачно.</p>
<p><a href="{% url 'main:register' %}">
    Зарегистрироваться повторно
</a></p>
{% endblock %}

site_practice/main/templates/main/by_rubric.html
{% extends "main/layout/basic.html" %}

{% load thumbnail %}
{% load static %}
{% load bootstrap4 %}

{% block title %}{{ rubric }}{% endblock %}

{% block content %}
<h2 class="mb-2">{{ rubric }}</h2>
<div class="conteiner-fluid mb-2">
    <div class="row">
        <div class="col">&nbsp;</div>
        <form class="col-md-auto form-inline">
            {% bootstrap_form form show_label=False %}
            {% bootstrap_button content='Искать' button_type='submit' %}
        </form>
    </div>
</div>
{% if bbs %}
<ul class="list-unstyled">
    {% for bb in bbs %}
    <li class="media my-5 p-3 border">
        {% url 'main:detail' rubric_pk=rubric.pk pk=bb.pk as url %}
        <a href="{{ url }}{{ all }}">
            {% if bb.image %}
            <img class="mr-3" src="{% thumbnail bb.image 'default' %}">
            {% else %}
            <img class="mr-3" src="{% static 'main/empty.jpg' %}">
            {% endif %}
        </a>
        <div class="media-body">
            <h3>
                <a href="{{ url }}{{ all }}"></a>
            </h3>
            <div>{{ bb.content }}</div>
            <p class="text-right font-weight-bold">{{ bb.price }} руб.</p>
            <p class="text-right font-italic">{{ bb.created_at }}</p>
        </div>
    </li>
    {% endfor %}
</ul>
{% bootstrap_pagination page url=keyword %}
{% endif %}
{% endblock %}

site_practice/main/templates/main/change_user_info.html
{% extends "main/layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Правка личных данных{% endblock %}

{% block content %}
<h2>Правка личных данных пользователя {{ user.username }}</h2>
<form method="post">
  {% csrf_token %}
  {% bootstrap_form form layout='horizontal' %}
  {% buttons submit='Сохранить' %}{% endbuttons %}
</form>
{% endblock %}

site_practice/main/templates/main/delete_user.html
{% extends "main/layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Удаление пользователя{% endblock %}

{% block content %}
<h2>Удаление пользователя {{ object.username }}</h2>
<form method="post">
  {% csrf_token %}
  {% buttons submit='Удалить' %}{% endbuttons %}
</form>
{% endblock %}

site_practice/main/templates/main/detail.html
{% extends "main/layout/basic.html" %}

{% load bootstrap4 %}
{% block title %}{{ bb.title }} - {{ bb.rubric.name }}{% endblock %}

{% block content %}
<div class="conteiner-fluid mt-3">
    <div class="row">
        {% if bb.image %}
            <div class="col-md-auto">
                <img src="{{ bb.image.url }}" class="main-image">
            </div>
        {% endif %}
        <div class="col">
            <h2>{{ bb.title }}</h2>
            <p>{{ bb.content }}</p>
            <p class="font-weight-bold">{{ bb.price }} руб.</p>
            <p>{{ bb.contacts }}</p>
            <p class="text-right font-italic">Добавлено {{ bb.created_at }}</p>
        </div>
    </div>
</div>
{% if ais %}
    <div class="d-flex justify-content-between flex-wrap mt-5">
        {% for ai in ais %}
            <div>
                <img class="additional-image" src="{{ ai.image.url }}">
            </div>
        {% endfor %}
    </div>
{% endif %}
<p>
    <a href="{% url 'main:by_rubric' pk=bb.rubric.pk %}{{ all }}">Назад</a>
</p>

<h4 class="mt-5">Новый комментарий</h4>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Добавить' %}{% endbuttons %}
</form>
{% if comments %}
<div class="mt-5">
    {% for comment in comments %}
    <div class="my-2 p-2 border">
        <h5>{{ comment.author }}</h5>
        <p>{{ comment.content }}</p>
        <p class="text-right font-italic">{{ comment.created_at }}</p>
    </div>
    {% endfor %}
</div>
{% endif %}
{% endblock %}

site_practice/main/templates/main/index.html
{% extends "main/layout/basic.html" %}

{% load thumbnail %}
{% load static %}

{% block content %}
<h2>Последние 10 объявлений</h2>
{% if bbs %}
<ul class="list-unstyled">
    {% for bb in bbs %}
    <li class="media my-5 p-3 border">
        {% url 'main:detail' rubric_pk=bb.rubric.pk pk=bb.pk as url %}
        <a href="{{ url }}{{ all }}">
            {% if bb.image %}
            <img class="mr-3" src="{% thumbnail bb.image 'default' %}">
            {% else %}
            <img class="mr-3" src="{% static 'main/images/empty.jpg' %}">
            {% endif %}
        </a>
        <div class="media-body">
            <h3>
                <a href="{{ url }}{{ all }}"></a>
            </h3>
            <div>{{ bb.content }}</div>
            <p class="text-right font-weight-bold">{{ bb.price }} руб.</p>
            <p class="text-right font-italic">{{ bb.created_at }}</p>
        </div>
    </li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

site_practice/main/templates/main/logout.html
{% extends "main/layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Выход{% endblock %}

{% block content %}
<h2>Вход</h2>
<p>Вы успешно вышли с сайта.</p>
{% endblock %}

site_practice/main/templates/main/password_change.html
{% extends "main/layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Смена пароля{% endblock %}

{% block content %}
<h2>Смена пароля пользователя {{ user.username }}</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Сменить пароль' %}{% endbuttons %}
</form>
{% endblock %}

site_practice/main/templates/main/profile.html
{% extends "main/layout/basic.html" %}

{% load thumbnail %}
{% load static %}
{% load bootstrap4 %}

{% block title %}Профиль пользователя{% endblock %}

{% block content %}
<h2>Профиль пользователя {{ user.username }}</h2>
{% if user.first_name and user.last_name %}
<p>Здравствуйте {{ user.first_name }} {{ user.last_name }}!</p>
{% else %}
<p>Здравствуйте!</p>
{% endif %}
<h3>Добавить объявление</h3>
<p>
    <a href="{% url 'main:profile_bb_add' %}">Добавить</a>
</p>
<h3>Ваши объявления</h3>
{% if bbs %}
<ul class="list-unstyled">
    {% for bb in bbs %}
    <li class="media my-5 p-3 border">
        {% url 'main:profile_bb_detail' pk=bb.pk as url %}
        <a href="{{ url }}{{ all }}">
            {% if bb.image %}
            <img class="mr-3" src="{% thumbnail bb.image 'default' %}">
            {% else %}
            <img class="mr-3" src="{% static 'main/images/empty.jpg' %}">
            {% endif %}
        </a>
        <div class="media-body">
            <h3>
                <a href="{{ url }}{{ all }}"></a>
            </h3>
            <div>{{ bb.content }}</div>
            <p class="text-right font-weight-bold">{{ bb.price }} руб.</p>
            <p class="text-right font-italic">{{ bb.created_at }}</p>
            <p class="text-right mt-2">
                <a href="{% url 'main:profile_bb_change' pk=bb.pk %}">Исправить</a>
                <a href="{% url 'main:profile_bb_delete' pk=bb.pk %}">Удалить</a>
            </p>
        </div>
    </li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

site_practice/main/templates/main/profile_bb_detail.html
{% extends "main/layout/basic.html" %}

{% block title %}{{ bb.title }} - Профиль пользователя{% endblock %}

{% block content %}
<div class="conteiner-fluid mt-3">
    <div class="row">
        {% if bb.image %}
            <div class="col-md-auto">
                <img src="{{ bb.image.url }}" class="main-image">
            </div>
        {% endif %}
        <div class="col">
            <h2>{{ bb.title }}</h2>
            <p>{{ bb.content }}</p>
            <p class="font-weight-bold">{{ bb.price }} руб.</p>
            <p>{{ bb.contacts }}</p>
            <p class="text-right font-italic">Добавлено {{ bb.created_at }}</p>
        </div>
    </div>
</div>
{% if ais %}
    <div class="d-flex justify-content-between flex-wrap mt-5">
        {% for ai in ais %}
            <div>
                <img class="additional-image" src="{{ ai.image.url }}">
            </div>
        {% endfor %}
    </div>
{% endif %}
<p>
    <a href="{% url 'main:profile' %}">Назад</a>
</p>
{% endblock %}

site_practice/main/templates/main/register_done.html
{% extends "main/layout/basic.html" %}

{% block title %}Регистрация завершена{% endblock %}

{% block content %}
<h2>Регистрация</h2>
<p>Регистрация пользователя завершена.</p>
<p>На адрес электронной почты выслано письмо для активации.</p>
{% endblock %}

site_practice/main/templates/main/register_user.html
{% extends "main/layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Регистрация{% endblock %}

{% block content %}
<h2>Регистрация нового пользователя</h2>
<form method="post">
  {% csrf_token %}
  {% bootstrap_form form layout='horizontal' %}
  {% buttons submit='Зарегистрироваться' %}{% endbuttons %}
</form>
{% endblock %}

site_practice/main/templates/main/user_is_activated.html
{% extends "main/layout/basic.html" %}

{% block title %}Пользователь уже активирован{% endblock %}

{% block content %}
<h2>Активация</h2>
<p>Пользователь с таким именем уже активирован.</p>
<p><a href="{% url 'main:login' %}">
    Войти на сайт
</a></p>
{% endblock %}